Refactor byte-run

diff --git a/byte-run b/byte-run
--- a/byte-run
+++ b/byte-run
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# Usage: algo-run elf flag_exectime flag_nodiff
+# Usage: algo-run elf flag_nodiff
 set -o pipefail
 
 info() {
@@ -7,15 +7,28 @@ info() {
 }
 
 pass() {
-  printf "\e[1;32m$*\e[m\n"
+  if [[ $# -eq 2 ]]; then
+    local time="$1"
+    shift
+    printf "$time \e[1;32m$*\e[m\n"
+  else
+    printf "\e[1;32m$*\e[m\n"
+  fi
 }
+
 
 warning() {
   printf "\e[1;33m$*\e[m\n"
 }
 
 error() {
-  printf "\e[1;31m$*\e[m\n"
+  if [[ $# -eq 2 ]]; then
+    local time="$1"
+    shift
+    printf "$time \e[1;31m$*\e[m\n"
+  else
+    printf "\e[1;31m$*\e[m\n"
+  fi
 }
 
 trap_ctrlc () {
@@ -28,7 +41,7 @@ print_header() {
 }
 
 print_banner() {
-  echo "-----------------------------------------------------{$*}---"
+  echo "--------------------------------------------------------{$*}---"
 }
 
 print_inp() {
@@ -40,6 +53,43 @@ print_inp() {
   echo "$raw"
 }
 
+handle_compre() {
+  local i=$1
+  local out=$2
+  local rel=$3
+  local inp=
+  local out=
+  echo "Input: "
+  print_inp "$i"
+  echo ""
+  diff -y -W 90 "$rel" "$out"
+  inp=$(cat "$i")
+  out=$(cat "$out")
+  rm -f *.rel *.inp *.out *.cmp
+  echo "$out" > 0.rel
+  echo "$inp" > 0.inp
+  echo "$inp" > $(basename $PWD).in
+}
+
+parse_debug_time() {
+  local raw=$(cat std_err.txt)
+  local real=$(echo "$raw" | awk '/real/ {print NR}')
+  local user=$(echo "$raw" | awk '/user/ {print NR}')
+  local sys=$(echo "$raw" | awk '/sys/ {print NR}')
+  if [[ "$((real + 1))" == "$user" && "$((real + 2))" == "$sys" ]]; then
+    running_time=$(echo "$raw" | \
+                   sed -n "$real,\$p" | \
+                   tr '\t' ' ' | \
+                   tr '\n' '@' | \
+                   sed 's/@/ \/ /g')
+    local debug=$((real - 1))
+    debug_info=$(echo "$raw" | sed -n "1,$debug p")
+  else
+    error "Not expect to reache here"
+    exit 1
+  fi
+}
+
 # When press ctrl+c, it will call `trap_ctrlc`.
 trap "trap_ctrlc" 2
 
@@ -48,8 +98,6 @@ target=$(basename $PWD)
 inputs=$(ls *.inp | sort -g)
 # File will be executed
 elf=${1:-elf}
-# Flag determines whether to show running time info after executed
-flag_exectime=${2:-0}
 # Flag determines whether to apply diff operation
 flag_nodiff=${3:-0}
 
@@ -66,9 +114,10 @@ total_cnt=0
 correct_cnt=0
 for i in $inputs; do
   # Print input samples
-  print_header "${i%.inp}"
+  print_header "input ${i%.inp}"
   if [[ $flag_compare -eq 0 && $flag_nodiff -eq 0 ]]; then
     # If this is my code and I want to see diff status
+    # echo "input: "
     print_inp "$i"
     print_banner "debug"
   fi
@@ -82,70 +131,44 @@ for i in $inputs; do
     rel="${i%.inp}".rel
   fi
 
-  # Execute
-  if [[ $flag_exectime -eq 0 ]]; then
-    cmd="gtimeout -s 2 5 ./$elf < $i"
-  else
-    cmd="gtimeout -s 2 5 time ./$elf < $i"
+  debug_info=
+  running_time=
+  if ! { bash -c "time ./$elf < $i"; } > "$out" 2>std_err.txt; then
+    error "Runtime error, Check source code, Please :(-"
+    exit 1
   fi
+  parse_debug_time std_err.txt
 
-  if [[ $flag_exectime -eq 0 ]]; then
-    if ! { bash -c "$cmd"; } > "$out"; then
-      error "Running error, timeout or memory issue occured :(-"
-      exit 1
-    elif [[ $flag_compare -eq 0 && $flag_nodiff -eq 0 ]]; then
-      print_banner "output"
-      cat "$out"
-    fi
-  else
-    if ! { bash -c "$cmd"; } > "$out" 2>time_info.txt; then
-      error "Running error, timeout or memory issue occured :(-"
-      exit 1
-    elif [[ $flag_compare -eq 0 && $flag_nodiff -eq 0 ]]; then
-      print_banner "time"
-      cat time_info.txt
-    fi
-    rm -f time_info.txt
+  if [[ $flag_compare -eq 0 && $flag_nodiff -eq 0 ]]; then
+    echo "$debug_info"
+    print_banner "output"
+    cat "$out"
   fi
 
   # Diff checking
-  if [[ -e "$rel" && $flag_nodiff -eq 0 && $flag_exectime -eq 0 ]]; then
+  if [[ -e "$rel" && $flag_nodiff -eq 0 ]]; then
     total_cnt=$((total_cnt + 1))
     if diff -y "$out" "$rel" >> /dev/null 2>&1; then
       correct_cnt=$((correct_cnt + 1))
-      if [[ $flag_compare -eq 0 ]]; then
-        pass "\\t\\t\\t\\t\\t\\tPassed"
-      fi
+      pass "$running_time" "PASSED"
     else
-      error "\\t\\t\\t\\t\\t\\tFailed"
+      error "$running_time" "Failed"
       print_banner "diff"
       if [[ $flag_compare -eq 1 ]]; then
         # If we found any difference in comparison mode, exit immediately.
-        echo "Input: "
-        print_inp "$i"
-        echo ""
-        diff -y -W 90 "$rel" "$out"
-        inp=`cat "$i"`
-        out=`cat "$out"`
-        rm -f *.rel
-        rm -f *.inp
-        rm -f *.out
-        rm -f *.cmp
-        echo "$out" > 0.rel
-        echo "$inp" > 0.inp
-        echo "$inp" > `basename $PWD`.in
+        handle_compre $i $out $rel
         exit 1
       elif [[ $flag_nodiff -eq 0 ]]; then
         diff -y -W 90 "$out" "$rel"
       fi
     fi
   elif [[ $flag_nodiff -eq 0 ]]; then
-    error "\\t\\t\\t\\t\\t\\tCustom"
+    error "$running_time" "Custom"
   fi
 done
-print_header ""
+print_header "all finished"
 
-if [[ $flag_exectime -eq 0 && $flag_nodiff -eq 0 ]]; then
+if [[ $flag_nodiff -eq 0 ]]; then
   if [[ $correct_cnt -eq $total_cnt ]]; then
     pass "ALL CASES PASSED! :-)"
   else
